#!/bin/sh
##########################################################################
# If not stated otherwise in this file or this component's Licenses.txt
# file the following copyright and licenses apply:
#
# Copyright 2016 RDK Management
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##########################################################################
### BEGIN INIT INFO
# Provides:          start-upnp-service
# Should-Start:
# Required-Start:    disable-hyperthreading
# Required-Stop:
# Default-Start:     3
# Default-Stop:
# Short-Description:
### END INIT INFO
# Defaults can be overridden in this file
INIT_SCRIPT_DEFAULTS_FILE="/etc/include.properties"
# Load alternate configuration if exists
if [ -f $INIT_SCRIPT_DEFAULTS_FILE ]; then
     . $INIT_SCRIPT_DEFAULTS_FILE
fi
# Defaults
INIT_SCRIPT_NAME="UPNP SERVICE"                  # full path to the executable
INIT_SCRIPT_EXECUTABLE=""                        # options to pass to the executable
INIT_SCRIPT_OPTIONS=""                           # a decriptive name
INIT_SCRIPT_HOMEDIR="/"                          # place where to cd before running
INIT_SCRIPT_PIDFILE=""                           # pid file name
INIT_SCRIPT_LOGFILE="applications.log"           # log file name
INIT_SLEEPTIME=""                                # how long to wait for startup and shutdown
. /etc/device.properties
XDISCOVERY_LOG="/rdklogs/logs/xdiscovery.log"
if [ "$LIGHTSLEEP_ENABLE" = "true" ]; then
     XDISCOVERY_PIPE="$TEMP_LOG_PATH/pipe_xdiscovery_log"
     count1=`find $TEMP_LOG_PATH -name pipe_xdiscovery_log -type f`
     if [ "$count1" != "" ]; then
           cat $XDISCOVERY_PIPE >> $XDISCOVERY_LOG
           echo "$XDISCOVERY_PIPE is not a pipe" >> $LOG_PATH/lightsleep.log
           rm -rf $XDISCOVERY_PIPE
     fi
     mkfifo $XDISCOVERY_PIPE &> /dev/null
     # Checking the logging pipe before startup
     value=`ps | grep $XDISCOVERY_PIPE | grep -v grep`
     if [ "$value" = "" ]; then
          cat $XDISCOVERY_PIPE >> $XDISCOVERY_LOG &
     fi
else
     XDISCOVERY_PIPE=$XDISCOVERY_LOG
fi

start_function() {
    pre_start "$INIT_SCRIPT_LOGFILE" ">>"
#    sh /etc/start_upnp.sh $XDISCOVERY_PIPE &
    sh /tmp/start_upnp.sh $XDISCOVERY_PIPE &
    post_start $?
}
stop_function() {
    pre_stop
    killall xcal-device
    killall xdiscovery
    sh /lib/rdk/processPID.sh /lib/rdk/start_upnp.sh | xargs kill -9
    post_stop 0
}

case "$1" in
  start)
    start_function
    ;;
  stop)
    stop_function
    ;;
  restart)
    $0 stop && $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
  ;;
esac


